const strings =
{
  "Cards": {
    "": {
      "pic_status": "a - assigned \ns - sketch \nF - final",
      "app_status": "X - don't use",
      "translate": "X - not now",
      "ship_icon": null,
      "name_en": null,
      "text_en": null,
      "clarification_en": "(for the [i] button)",
      "future text (for expansion stuff)": null,
      "name_de": null,
      "text_de": null,
      "clarification_de": null,
      "future_de": null,
      "name_cs": null,
      "text_cs": null,
      "clarification_cs": null,
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": null,
      "text_fr": null,
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": null,
      "text_jp": null,
      "clarification_jp": null,
      "future_jp": null,
      "name_ko": null,
      "text_ko": null,
      "clarification_ko": "([i] 버튼)",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": null,
      "text_ru": null,
      "clarification_ru": null,
      "future_ru": null
    },
    "metal_fatigue": {
      "pic_status": "a",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Metal Fatigue",
      "text_en": "After each adventure, if anyone gained or lost flight days, roll a die. For all ships that moved that much or more, roll for coordinates. The component at those coordinates falls off.",
      "clarification_en": null,
      "future text (for expansion stuff)": null,
      "name_de": "Marodes Metall",
      "text_de": "Würfelt nach jedem Abenteuer, falls jemand in diesem Flugtage gewonnen oder verloren hat. Bei allen Schiffen, die sich so weit oder weiter bewegt habe wie der Koordinatenwurf, fällt das Bauteil an diesen Koordinaten ab.",
      "clarification_de": null,
      "future_de": null,
      "name_cs": "Únava materiálu",
      "text_cs": "Po vyhodnocení každé karty, na které někdo ztratil nebo získal letové dny, hoďte kostkou. Pak pro všechny lodě, které se posunuly o alespoň tolik letových dní, určete hodem souřadnice. Dílek na těchto souřadnicích odpadá.",
      "clarification_cs": null,
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Faiblesse structurelle",
      "text_fr": "Après chaque aventure, si au moins un joueur a gagné ou perdu des jours de vol, lancez un dé. Pour chaque vaisseau qui s'est déplacé d'un nombre de cases supérieur ou égal au résultat, déterminez les coordonnées par un lancer de dés : le composant présent à ces coordonnées tombe.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "金属疲労",
      "text_jp": "各アドベンチャーの解決後、誰か航海日数を費やした/稼いだプレイヤーが居たらダイス1個を振る。出目以上のスペース数を移動した各宇宙船は縦/横列のダイスを振り交差点を決める。交差点のスペースにパーツがあれば落下する。",
      "clarification_jp": null,
      "future_jp": null,
      "name_ko": "마모된 부품",
      "text_ko": "모험 카드의 실행이 끝날 때마다, 비행 일수를 얻거나 잃은 사람이 있으면 주사위 하나를 굴립니다. 주사위 결과만큼, 또는 그 이상 이동한 모든 우주선에 대해 주사위를 굴려서 좌표를 정합니다. 해당하는 좌표의 부품이 분리됩니다.",
      "clarification_ko": null,
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Усталость металла",
      "text_ru": "После каждого происшествия, в котором кто-то нагнал или потерял дни полёта, бросьте кубик. Каждый корабль, который переместился на расстояние, равное или превышающее результат броска, теряет по модулю (бросьте кубики дважды, чтобы определить его координаты).",
      "clarification_ru": null,
      "future_ru": null
    },
    "explosive_stuff": {
      "pic_status": "a",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Explosive Stuff",
      "text_en": "If a component with goods or a battery token is destroyed, all components in the eight neighboring squares are also destroyed. This may cause a chain reaction.",
      "clarification_en": "- This applies only to components which are destroyed (by cannon fire, meteors, sabotage, or explosions) and not to those which fall off.\n- If components with goods or batteries are destroyed in the explosion, they will also explode.\n- Empty cargo holds or battery components do not explode.",
      "future text (for expansion stuff)": null,
      "name_de": "Detonierende Dinge",
      "text_de": "Wird ein Bauteil mit Gütern oder Batteriemarker zerstört, werden auch alle Bauteile in den 8 benachbarten Feldern zerstört. Das kann zu Kettenreaktionen führen.",
      "clarification_de": "Das gilt nur für Bauteile, die zerstört werden (durch Kanonenfeuer, Meteore, Sabotage oder Explosionen) und nicht für solche, die abfallen.\n Wenn Bauteile mit Gütern oder Batterien durch die Explosion zerstört werden, explodieren auch sie.",
      "future_de": null,
      "name_cs": "Výbušné zboží",
      "text_cs": "Pokud je zničen dílek se zbožím nebo bateriemi, zničí se zároveň i všech 8 sousedních dílků. To může vyvolat řetězovou reakci.",
      "clarification_cs": "- Vztahuje se pouze na zničené komponenty (střelou, meteorem, sabotáží nebo výbuchem). Netýká se odpadlých dílků.\n- Dílky se zbožím nebo bateriemi zničené výbuchem také vybuchnou.\n- Prázdné kontejnery nebo vyčerpané baterie nevybuchují.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Trucs explosifs",
      "text_fr": "Si un composant contenant au moins une marchandise ou une cellule d'énergie est détruit, les composants des huit cases adjacentes sont également détruits. Cela peut déclencher une réaction en chaîne.",
      "clarification_fr": "Cela ne s'applique qu'aux composants qui sont détruits (par des tirs de canons, des  astéroïdes, un sabotage ou une explosion) et non pas à ceux qui tombent. Si un composant contenant des marchandises ou des cellules d'énergie est détruit par l'explosion, il déclenche alors une autre explosion.",
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "爆発物",
      "text_jp": "商品またはバッテリー・トークンが置かれたパーツが破壊された場合、爆発してその周囲8つのスペースにあるパーツも破壊される。これは連鎖する可能性がある。",
      "clarification_jp": "- これは（レーザー砲撃/流星/破壊工作/爆発により）破壊されたパーツにのみ適用され、落下した場合には適用されない。\n - もしも爆発で【商品またはバッテリー・トークンが置かれたパーツ】が破壊されたら、そのパーツも爆発する。\n - カラの〈貨物室〉や〈バッテリーパック〉は爆発しない。",
      "future_jp": "これは（レーザー砲撃/流星/破壊工作/爆発により）破壊されたパーツにのみ適用され、落下した場合には適用されない。\n もしも爆発で【商品またはバッテリー・トークンが置かれたパーツ】が破壊されたら、そのパーツも爆発する。\n カラの〈貨物室〉や〈バッテリーパック〉は爆発しない。",
      "name_ko": "폭발물",
      "text_ko": "상품이나 배터리 토큰이 있는 부품이 파괴되면 인접한 8개의 칸에 있는 부품도 모두 파괴됩니다. 이것은 연쇄 반응을 일으킬 수 있습니다.",
      "clarification_ko": "- (대포 사격, 유성군, 사보타주 또는 폭발에 의해) 파괴된 부품에만 적용되며, 분리되는 부품에는 적용되지 않습니다.\n- 상품 또는 배터리 토큰이 있는 부품이 폭발해서 파괴되면 해당 부품도 폭파됩니다.\n- 빈 화물칸이나 빈 배터리 부품은 폭발하지 않습니다.",
      "future_ko": "이것은 (대포 사격, 유성군, 사보타주, 폭발에 의해) 파괴된 부품에만 적용되며, 분리되거나 포기한 부품에는 적용되지 않습니다.\n상품 또는 배터리 토큰이 있는 부품이 폭발해서 파괴되면 해당 부품도 폭파됩니다.\n빈 화물칸이나 빈 배터리 부품은 폭발하지 않습니다.",
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Не кантовать!",
      "text_ru": "Если на вашем корабле уничтожили модуль с грузами или батареями, он взрывается: также уничтожьте все 8 модулей вокруг этого модуля. Это может спровоцировать цепную реакцию.",
      "clarification_ru": "- Срабатывает, только если модуль был уничтожен (выстрелом, метеором, взрывом или из-за саботажа). Если модуль просто отваливается, ничего не происходит.\n- Если взрыв уничтожает другой модуль с грузами или батареями, он тоже взрывается.\n- Модуль не взрывается, если в нём нет грузов или батарей.",
      "future_ru": "Срабатывает, только если модуль был уничтожен (выстрелом, метеором, взрывом или из-за саботажа). Если модуль просто отваливается, ничего не происходит.\nЕсли взрыв уничтожает другой модуль с грузами или батареями, он тоже взрывается.\nМодуль не взрывается, если в нём нет грузов или батарей."
    },
    "paranoid_locals": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Paranoid Locals",
      "text_en": "Anyone who wants to land on a planet first takes one blast of light cannon fire from the front. If only one player wants to land, make it heavy cannon fire.",
      "clarification_en": "- Everyone decides in order. Then roll. Then load goods.",
      "future text (for expansion stuff)": null,
      "name_de": "Paranoide Personen",
      "text_de": "Jeder, der auf einem Planeten landen will, erhält zuvor einen Schuss leichtes Kanonenfeuer von vorn. Falls nur 1 Spieler landen will, ist es schweres Kanonenfeuer.",
      "clarification_de": "Entscheidet euch in Flugreihenfolge. Dann würfelt. Dann ladet Güter.",
      "future_de": null,
      "name_cs": "Nepřátelští obyvatelé",
      "text_cs": "Každý, kdo chce přistát na planetě, musí předtím čelit jedné malé střele zepředu. Pokud chce přistát pouze jediný hráč, musí čelit velké střele.",
      "clarification_cs": "- Hráči se rozhodují v pořadí. Pak hoďte kostkami. Pak nakládejte zboží.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Habitants paranoïaques",
      "text_fr": "Tout pilote souhaitant atterrir sur une planète subit au préalable un tir de canon léger venant de l'avant. Si un seul joueur décide d'atterrir, il subit un tir de canon lourd à la place.",
      "clarification_fr": "Chaque joueur se décide dans l'ordre. Lancez ensuite les dés une fois pour tous les joueurs. Puis, chargez vos marchandises.",
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "被害妄想の現地人",
      "text_jp": "惑星への着陸を望む各プレイヤーは、まず前方からのレーザー砲撃（弱）1回を受ける。ただし着陸を望むのが1人だけの場合は、代わりにレーザー砲撃（強）を受ける。",
      "clarification_jp": "- 各プレイヤーは「順番に」決定する。次にダイスを振る。それから商品を積み込む。",
      "future_jp": null,
      "name_ko": "현지인의 편집증",
      "text_ko": "행성에 착륙하려는 사람은 먼저 정면에서 오는 약한 사격 한 발을 맞아야 합니다. 착륙하려는 플레이어가 한 명뿐이면 강한 사격을 당합니다.",
      "clarification_ko": "- 착륙할 것인지 순서대로 정합니다. 그런 다음, 주사위를 굴립니다. 그 후에 상품을 싣습니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Прохладный приём",
      "text_ru": "Игрок, который первым решит приземлиться на новой планете, получает приветственный залп из мелкокалиберной пушки спереди. Если кроме него никто больше не захотел приземляться, залп становится крупнокалиберным.",
      "clarification_ru": "- Сначала решите, кто хочет приземлиться (в порядке очерёдности). Затем бросьте кубики для выстрела, а после этого грузите товары.",
      "future_ru": null
    },
    "cosmic_psychosis": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Cosmic Psychosis",
      "text_en": "After each adventure, roll for coordinates. If the roll indicates a cabin with one or more human crew members (not aliens), they go insane and the cabin is destroyed.",
      "clarification_en": "- Roll for coordinates as with the Sabotage adventure, but only once for all players.",
      "future text (for expansion stuff)": null,
      "name_de": "Kosmischer Koller",
      "text_de": "Nach jedem Abenteuer erwürfelt ihr Koordinaten. Befinden sich dort Kabinen mit mindest einem menschlichen Crewmitglied (keine Aliens), werden diese Crewmitglieder verrückt und die Kabine zerstört.",
      "clarification_de": "Erwürfelt die Koordinaten wie beim Sabotage-Abenteuer, jedoch nur einmal für alle Trucker.",
      "future_de": null,
      "name_cs": "Vesmírná psychóza",
      "text_cs": "Po vyhodnocení každé karty určete hodem souřadnice. Pokud se na těchto souřadnicích nachází kajuta s alespoň jedním kosmonautem (ne mimozemšťanem), ten se zblázní a kabinu zničí.",
      "clarification_cs": "- Házejte stejně jako při vyhodnocení Sabotáže, ale pouze jednou a pro všechny hráče zároveň.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Psychose cosmique",
      "text_fr": "Après chaque aventure, lancez les dés pour déterminer les coordonnées. Si le résultat désigne une cabine occupée par un ou plusieurs humains (pas des extraterrestres), ils deviennent fous et la cabine est détruite.",
      "clarification_fr": "Déterminez les coordonnées comme pour un Sabotage, mais une fois seulement pour tous les joueurs.",
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "宇宙幻覚症",
      "text_jp": "各アドベンチャーの解決後、ダイスを振り交差点を決める。交差点のスペースに船室があり、さらに地球人の乗組員（異星人は対象外）が1人以上いた場合には、乗組員は正気を失ってその船室は破壊される。",
      "clarification_jp": "- アドベンチャー《破壊工作》と同様に交差点を決めるが、ただし全員の分を1回だけが振る。",
      "future_jp": null,
      "name_ko": "우주 정신병",
      "text_ko": "모험 카드의 실행이 끝날 때마다, 주사위를 굴려서 좌표를 정합니다. 좌표가 한 명 이상의 인간 승무원이 있는 선실을 가리키면, 승무원은 미쳐버리고 선실이 파괴됩니다.",
      "clarification_ko": "- 사보타주 모험 카드처럼 주사위를 굴려서 좌표를 정하지만, 한 번만 굴려서 모든 플레이어에게 적용합니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Космическое безумие",
      "text_ru": "После каждого происшествия бросайте два кубика, чтобы определить координаты. Если на вашем корабле по этим координатам есть хотя бы один космонавт (не инопланетянин), то все обитатели каюты сходят с ума. Уничтожьте модуль этой каюты.",
      "clarification_ru": "- Бросьте оба кубика дважды (как во время саботажа), но для всех игроков.",
      "future_ru": null
    },
    "personalized_cabins": {
      "pic_status": "a",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Personalized Cabins",
      "text_en": "Each cabin is owned by its crew, so you pay no end-of-flight penalties for lost cabins. When you give up crew, remove their cabins from the ship (even if another crew member still lives there).",
      "clarification_en": "- First give up the crew members, then resolve the removal of their cabins.\n- Removed cabins do not count as \"destroyed\" or \"fallen off\".\n- Put lost or removed cabins in the general component pile, not your discard pile.\n- This applies even to cabins left in your reserve after building.",
      "future text (for expansion stuff)": null,
      "name_de": "Crew-Kabinen",
      "text_de": "Die Kabinen sind im Besitz ihrer Crew, müssen also nicht bezahlt werden, wenn sie verloren gehen. Immer wenn du 1 oder mehr Crewmitglieder verlierst, gibst du auch deren Kabinen auf ( inklusive des Astronauten, der sich darin eventuell noch befindet).",
      "clarification_de": "Zuerst gibst du die Crewmitglieder auf (inkl. Aliens), dann ihre Kabinen.\n Kabinen, die (egal wie) verloren wurden, kommen in den Vorrat zurück, nicht zu deinen verlorenen Teilen.",
      "future_de": null,
      "name_cs": "Personalizované kajuty",
      "text_cs": "Kajuty patří posádce, za ztracené neplatíte. Kdykoliv přijdete o nějakého člena posádky, přijdete zároveň i o jeho kajutu (včetně druhého kosmonauta, pokud v ní zbyl).",
      "clarification_cs": "- Nejdříve si zvolte, jaké všechny členy posádky ztratíte (včetně mimozemšťanů), pak odstraňte i jejich kajuty.\n- Kajuty, o které přijdete jakýmkoliv způsobem, se nepočítají jako ztracené dílky.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Cabines personnalisées",
      "text_fr": "Les cabines appartiennent à leurs occupants et ne sont pas comptées comme des composants perdus. Si vous perdez un ou plusieurs membres d'équipage, abandonnez également leur cabine (ainsi que tout éventuel astronaute restant).",
      "clarification_fr": "Commencez par abandonner tous les membres d'équipage (y compris les extraterrestres), puis leur cabine. Quelle qu'en soit la raison, les cabines perdues sont remises dans la pile centrale et non dans votre défausse de composants perdus.",
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "オーダーメイド船室",
      "text_jp": "船室は搭乗している乗組員の所有物であり、失ったパーツの損害賠償は支払わない。あなたが1人以上の乗組員を失った際は常に、その置かれていた船室も取り除く（そこに別の乗組員もあればそれも含めて失う）。",
      "clarification_jp": "- まず最初に（異星人も含め）そこにいる乗組員を全員失い、次に船室を取り除く。\n - 船室が取り除かれた場合は、理由に関係なく「失われたパーツ」には置かずに山札に戻す。",
      "future_jp": null,
      "name_ko": "개인 선실",
      "text_ko": "선실은 승무원의 것이며, 잃은 부품으로 취급하지 않습니다. 한 명 이상의 승무원을 잃을 때마다 선실도 포기합니다(해당 선실에 남은 승무원이 있으면 그 승무원도 포기합니다).",
      "clarification_ko": "- 우선, 외계인을 포함한 모든 승무원을 포기합니다. 그런 다음, 선실을 포기합니다.\n- 이렇게 잃은 선실은 자신의 버리는 부품 칸이 아니라 부품 더미로 돌아갑니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Личные каюты",
      "text_ru": "Члены экипажа выкупили свои каюты заранее. Так что потерянные каюты не отправляются в утиль. Когда из каюты пропадает хотя бы один член экипажа, каюта отваливается от корабля (вместе со вторым членом экипажа, если он есть).",
      "clarification_ru": "- Сначала верните потерянный экипаж в запас (включая инопланетян), затем их каюты отваливаются.\n- Уничтоженные и отвалившиеся каюты возвращаются в запас. Они не попадают в утиль.",
      "future_ru": null
    },
    "tough_trip": {
      "pic_status": "F",
      "app_status": "X",
      "translate": "X",
      "ship_icon": null,
      "name_en": "Tough Trip",
      "text_en": null,
      "clarification_en": null,
      "future text (for expansion stuff)": null,
      "name_de": null,
      "text_de": null,
      "clarification_de": null,
      "future_de": null,
      "name_cs": "Náročný výlet",
      "text_cs": null,
      "clarification_cs": null,
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": null,
      "text_fr": null,
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "大変な旅",
      "text_jp": null,
      "clarification_jp": null,
      "future_jp": null,
      "name_ko": null,
      "text_ko": null,
      "clarification_ko": null,
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Нелёгкая дорога",
      "text_ru": null,
      "clarification_ru": null,
      "future_ru": null
    },
    "meteoric_inversion": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Meteoric Inversion",
      "text_en": "Large meteors are small, and small meteors are large.",
      "clarification_en": null,
      "future text (for expansion stuff)": null,
      "name_de": "Invertierte Meteore",
      "text_de": "Große Meteoriten sind klein und kleine Meteoriten sind groß.",
      "clarification_de": null,
      "future_de": null,
      "name_cs": "Meteorická inverze",
      "text_cs": "Velké meteory jsou malé, malé jsou velké.",
      "clarification_cs": null,
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Inversion météoritique",
      "text_fr": "Les gros astéroïdes sont considérés comme petits, et les petits astéroïdes sont considérés comme gros.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "流星逆転現象",
      "text_jp": "流星（大）は流星（小）として扱い、流星（小）は流星（大）として扱う。",
      "clarification_jp": null,
      "future_jp": null,
      "name_ko": "유성군 반전",
      "text_ko": "큰 유성은 작은 유성이 되고, 작은 유성은 큰 유성이 됩니다.",
      "clarification_ko": null,
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Метеоритная инверсия",
      "text_ru": "Вместо больших метеоритов в вас летят малые, а вместо малых — большие.",
      "clarification_ru": null,
      "future_ru": null
    },
    "remorseless_fate": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Remorseless Fate",
      "text_en": "Combat Zones and Sabotage affect all players except the one who has the most. Cabins affected by Epidemics must be given up. In Stardust, instead of losing flight days, components with exposed connectors fall off.",
      "clarification_en": "- For example, Sabotage affects everyone except the player with the most crew; roll 3 times, but players hit by one roll ignore the remaining rolls. If everyone is tied, only the player farthest behind is unaffected.",
      "future text (for expansion stuff)": null,
      "name_de": "Schonungsloses Schicksal",
      "text_de": "Kampfzone und Sabotage betreffen alle Spieler außer dem, der das meiste hat. Kabinen, die von Epidemien betroffen sind, müssen aufgegeben werden. Bei Sternenstaub verliert man keine Flugtage, stattdessen fallen Bauteile mit freiliegenden Anschlüssen ab.",
      "clarification_de": "Kampfzone und Sabotage betreffen alle Spieler außer dem, der das meiste hat. Kabinen, die von Epidemien betroffen sind, müssen aufgegeben werden. Bei Sternenstaub verliert man keine Flugtage, stattdessen fallen Bauteile mit freiliegenden Anschlüssen ab.",
      "future_de": null,
      "name_cs": "Nelítostný osud",
      "text_cs": "Bojové zóny a Sabotáže postihují všechny hráče kromě těch, kteří měli v porovnávání nejvíce. O kajuty postižené Epidemií přijdete. U Hvězdného prachu dílky s otevřenými přípojkami odpadnou místo toho, abyste ztráceli letové dny.",
      "clarification_cs": "- Například Sabotáž postihne všechny kromě hráče, který má nejvíce posádky. Hoďte až třikrát, ale hráči zasažení jedním hodem už další hody ignorují. V případě remízy postihuje karta všechny hráče kromě toho, který je nejvíce vzadu.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Destin Impitoyable",
      "text_fr": "Les cartes Zone de combat et Sabotage affectent tous les joueurs, sauf celui qui est majoritaire. Les cabines affectées par une Épidémie doivent être abandonnées. Pour la Poussière d'étoiles, au lieu de perdre des jours de vol, les composants avec des connecteurs exposés tombent du vaisseau.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "無慈悲な運命",
      "text_jp": "《交戦宙域》と《破壊工作》は、最上位のプレイヤーを除く全員が効果を受ける。《伝染病発生》で効果を受けた船室は取り除く必要がある。《宇宙塵》は航海日数を費やす代わりに、〈露出したコネクタ〉を持つパーツが落下する。",
      "clarification_jp": "- 例えば、《破壊工作》は【乗組員が最も多い】プレイヤー以外の全員が効果を受ける； 計3回まで振りなおすが、1回でも直撃を受けたプレイヤーは以後の出目は無視する。もしも全員が同点なら、最後尾のプレイヤー1人だけが効果を受けない。",
      "future_jp": null,
      "name_ko": "무자비한 운명",
      "text_ko": "교전 지대와 사보타주는 가장 수치가 높은 플레이어를 제외한 모든 플레이어에게 영향을 미칩니다. 전염병의 영향을 받는 선실은 포기해야 합니다. 우주 먼지에서는 비행 일수를 잃는 대신, 노출된 연결 장치가 있는 부품이 분리됩니다.",
      "clarification_ko": null,
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Безжалостная судьба",
      "text_ru": "Эффекты саботажа и зон конфликта действуют на всех, кроме сильнейшего по соответствующему показателю игрока. Каюты, затронутые эпидемией, отваливаются от кораблей. Вы не теряете дни полёта в звёздной пыли: вместо этого все модули с оголёнными разъёмами отваливаются от кораблей.",
      "clarification_ru": "- Например, саботаж влияет на всех, кроме корабля с самым многочисленным экипажем. Определите координаты трижды (но игнорируйте оставшиеся координаты после того, как пострадаете). Если все игроки равны по соответствующему показателю, пострадать придётся всем, кроме летящего самым последним.",
      "future_ru": null
    },
    "stiff_competition": {
      "pic_status": null,
      "app_status": "X",
      "translate": "X",
      "ship_icon": null,
      "name_en": "Stiff Competition",
      "text_en": null,
      "clarification_en": null,
      "future text (for expansion stuff)": null,
      "name_de": null,
      "text_de": null,
      "clarification_de": null,
      "future_de": null,
      "name_cs": "Tvrdá konkurence",
      "text_cs": null,
      "clarification_cs": null,
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": null,
      "text_fr": null,
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "競争激化",
      "text_jp": null,
      "clarification_jp": null,
      "future_jp": null,
      "name_ko": null,
      "text_ko": null,
      "clarification_ko": null,
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Жёсткая конкуренция",
      "text_ru": null,
      "clarification_ru": null,
      "future_ru": null
    },
    "big_baddies": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Big Baddies",
      "text_en": "Whenever you encounter enemies, roll two dice and add the lower die to the enemy’s strength.",
      "clarification_en": null,
      "future text (for expansion stuff)": null,
      "name_de": "Brutale Bösewichte",
      "text_de": "Immer wenn du Feinden begegnest, würfle mit 2 Würfeln und addiere das niedrigere Ergebnis zur Stärke der Feinde.",
      "clarification_de": null,
      "future_de": null,
      "name_cs": "Velcí zlouni",
      "text_cs": "Kdykoliv narazíte na nepřátele, hoďte dvěma kostkami a nižší hodnotu přidejte k jejich síle.",
      "clarification_cs": null,
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Grands méchants",
      "text_fr": "Lorsque vous rencontrez un ennemi, lancez deux dés et ajoutez la valeur du plus faible à la force de l'ennemi.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "手強い敵船",
      "text_jp": "あなたが敵船と遭遇した際は常に、ダイス2個を振って小さい方の出目を敵船のパワーに追加する。",
      "clarification_jp": null,
      "future_jp": null,
      "name_ko": "나쁜 녀석들",
      "text_ko": "적을 마주칠 때마다, 주사위 두 개를 굴려서 작게 나온 주사위 결과를 적의 화력이나 출력에 더합니다.",
      "clarification_ko": null,
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Пушки побольше",
      "text_ru": "Когда на пути возникает вражеский корабль, бросьте два кубика и прибавьте меньший результат к мощности пушек этого корабля.",
      "clarification_ru": null,
      "future_ru": null
    },
    "engine_envy": {
      "pic_status": null,
      "app_status": "X",
      "translate": "X",
      "ship_icon": null,
      "name_en": "Welcome to the Lead",
      "text_en": "Whenever a player passes the leader, the former leader may choose one cannon (pay 1 battery token, if neccessary) to shoot the new leader. The new leader receives light cannon fire in that row or column from the corresponding direction.",
      "clarification_en": "- For example, if you choose a forward-pointing cannon, your opponent is hit in the rear; if you choose a left-pointing cannon, your opponent is hit from the right, etc.\n- It's just one blast of light cannon fire, even if a double cannon is used.",
      "future text (for expansion stuff)": null,
      "name_de": null,
      "text_de": null,
      "clarification_de": null,
      "future_de": null,
      "name_cs": "Nepřející soupeři",
      "text_cs": "Kdykoliv se do vedení dostane nový hráč, hráč za ním se může rozhodnout na něj vystřelit. Zvolí si jedno ze svých děl (za dvojité musí zaplatit baterii) a soupeř čelí malé střele v daném sloupci nebo řádku z odpovídajícího směru.",
      "clarification_cs": "- Např. pokud si vyberete dělo mířící dopředu, zasáhnete vedoucího hráče zezadu. Když si vyberete dělo mířící doleva, zasáhnete jej zprava atp.\n- Jde vždy jen o jednu malou střelu, i v případě dvojitého děla.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": null,
      "text_fr": null,
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "追う者と追われる者",
      "text_jp": "リーダーが別のプレイヤーに変わるたび、直後にいるプレイヤーはその宇宙船を砲撃してもよい。新たなリーダーに対し、自分の宇宙船のレーザー砲1基（ダブルレーザー砲ならコストを支払う）から、その縦列/横列でレーザー砲撃（弱）を発射する（砲撃は発射した面と逆の面から相手に直撃する）。",
      "clarification_jp": "- つまり、あなたが前方から砲撃したら相手の後方に直撃し、あなたが左側面から砲撃したなら相手の右側面に直撃、等々。",
      "future_jp": null,
      "name_ko": "질투나는 엔진",
      "text_ko": "새 플레이어가 선두가 될 때마다, 바로 뒤의 플레이어는 자신의 대포(이중 대포는 배터리 지불) 하나를 선택하여 선두에게 약한 사격을 할 수 있습니다. 선택한 대포에 해당하는 세로줄 또는 반대편 가로줄로 사격합니다.",
      "clarification_ko": "- 즉, 앞쪽 대포를 선택하면 선두의 후미에, 왼쪽 대포를 선택하면 선두의 오른쪽에 사격합니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Манёвры при обгоне",
      "text_ru": "Когда кто-то из игроков становится лидером, корабль, который оказался позади него, может выстрелить по нему из одной пушки. Двойную пушку нужно при этом обеспечить энергией. Выстрел считается мелкокалиберным и прилетает со стороны, противоположной направлению выстрела: если пушка направлена влево — справа, если вперёд — сзади и т.д.",
      "clarification_ru": "- Выстрел считается мелкокалиберным и прилетает лидеру со стороны, противоположной направлению выстрела: если пушка направлена влево — справа, если вперёд — сзади и т.д.",
      "future_ru": null
    },
    "piercing_projectiles": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Piercing Projectiles",
      "text_en": "If a meteor or cannon fire destroys the first component it hits, it will also hit the next component in line.",
      "clarification_en": "- The second hit usually destroys the second component, too, but a small meteor will bounce off the second component if it hits a smooth side.",
      "future text (for expansion stuff)": null,
      "name_de": "Durchschlagende Projektile",
      "text_de": "Zerstört ein Meteorit oder Kanonenfeuer das erste getroffene Bauteil, wird auch das dahinter liegende Bauteil getroffen.",
      "clarification_de": "Zerstört ein Meteorit oder Kanonenfeuer das erste getroffene Bauteil, wird auch das dahinter liegende Bauteil getroffen.",
      "future_de": null,
      "name_cs": "Průrazné střely",
      "text_cs": "Když meteor nebo střela zničí nějaký dílek, zasáhne zároveň i další dílek v daném směru.",
      "clarification_cs": "- Druhý dílek je většinou také zničen. Pokud je ale nastaven prázdnou hranou, malý meteor se od ní odrazí.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Projectiles perforants",
      "text_fr": "Si un astéroide ou un tir de canon détruit le premier composant qu'il touche, il poursuit sa course et touche également le composant suivant dans l'alignement.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "貫通弾",
      "text_jp": "もしも流星やレーザー砲撃が最初に直撃したパーツを破壊した場合は、その同じ列にある次のパーツにも直撃する。",
      "clarification_jp": "- 2番目の直撃は通常どおり2番目のパーツも破壊するが、ただし、2番目のパーツの外装面を直撃した流星（小）は跳ね返される。",
      "future_jp": null,
      "name_ko": "관통 발사체",
      "text_ko": "만약 유성이나 사격이 타격한 첫 번째 부품을 파괴하면, 그 줄의 다음 부품도 타격합니다.",
      "clarification_ko": "- 일반적으로 두 번째 타격이 두 번째 부품도 파괴하지만, 작은 유성이 두 번째 부품의 매끈한 면을 타격한 경우에는 튕겨 나옵니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Лёгкая защита",
      "text_ru": "Если метеорит или выстрел уничтожает модуль, он также попадает в следующий по направлению модуль.",
      "clarification_ru": "- Скорее всего, второй модуль также будет уничтожен. Но помните, что малый метеорит отскочит от гладкой стороны модуля даже в таких условиях.",
      "future_ru": null
    },
    "union_ship": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Union Ship",
      "text_en": "Before revealing the final adventure card, either give up on the flight or pay 1 credit or 1 goods block per crew member.",
      "clarification_en": "- The crew’s labor union will not accept batteries instead of goods.\n- If you do not have enough goods and credits, you must give up.",
      "future text (for expansion stuff)": null,
      "name_de": "Gewerkschafts-Schiff",
      "text_de": "Vor dem Aufdecken der letzten Abenteuerkarte gibst du entweder den Flug auf oder bezahlst 1 Credit oder 1 Güter-Block pro Crewmitglied.",
      "clarification_de": "Vor dem Aufdecken der letzten Abenteuerkarte gibst du entweder den Flug auf oder bezahlst 1 Credit oder 1 Güter-Block pro Crewmitglied.",
      "future_de": null,
      "name_cs": "Odborářská loď",
      "text_cs": "Předtím, než otočíte poslední letovou kartu, musíte buď odstoupit z letu, nebo zaplatit 1 kredit nebo 1 zboží za každého člena posádky.",
      "clarification_cs": "- Odbory nepřijímají baterie místo zboží.\n- Pokud nemáte dost zboží nebo kreditů, musíte odstoupit z letu.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Vaisseau de syndiqués",
      "text_fr": "Avant de révéler la dernière carte Aventure, vous devez soit abandonner le vol, soit payer 1 crédit ou 1 cube Marchandise par membre d'équipage.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "宇宙船員労働組合",
      "text_jp": "最後のアドベンチャー・カードを公開する直前に、航海をギブアップするか、または、乗組員1人につき1クレジットまたは商品ブロック1個を支払う。",
      "clarification_jp": "- 乗組員の属する労働組合は、商品の代用でバッテリーは受け取らない。\n - もしも十分な商品/クレジットを持っていないなら、あなたはギブアップするしかない。",
      "future_jp": null,
      "name_ko": "우주선 노조",
      "text_ko": "최종 모험 카드를 공개하기 전에, 비행을 포기하거나 승무원 하나당 1 크레딧 또는 상품 1개를 지불합니다.",
      "clarification_ko": "- 승무원 노조는 상품 대신 배터리를 받지 않습니다.\n- 상품과 크레딧이 충분하지 않으면 비행을 포기해야 합니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Профсоюз",
      "text_ru": "Когда в колоде происшествий останется 1 карта, потеряйте 1 кредит или 1 товар за каждого члена экипажа на корабле. В противном случае вам придётся сдаться.",
      "clarification_ru": "- Профсоюз не принимает батареи вместо товаров.\n- Если у вас не хватает кредитов и товаров, чтобы расплатиться с профсоюзом, вы будете вынуждены сдаться.",
      "future_ru": null
    },
    "bad_luck": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Bad Luck",
      "text_en": "If a roll of the dice for a meteor or cannon fire indicates that no one is hit or forced to use a battery, roll again, up to three rolls total.",
      "clarification_en": "- A small meteor that bounces off counts as a hit and does not cause you to roll again.",
      "future text (for expansion stuff)": null,
      "name_de": "Großes Pech",
      "text_de": "Wird beim Würfelwurf für einen Meteor oder Kanonenfeuer niemand getroffen oder es muss keine Batterie ausgegeben werden, würfle erneut – bis zu insgesamt drei Würfen.",
      "clarification_de": "Wird beim Würfelwurf für einen Meteor oder Kanonenfeuer niemand getroffen oder es muss keine Batterie ausgegeben werden, würfle erneut – bis zu insgesamt drei Würfen.",
      "future_de": null,
      "name_cs": "Smůla",
      "text_cs": "Když hod na meteor nebo střelu nikoho nezasáhne (nebo nikdo nemusí použít baterii), hoďte znovu, maximálně třikrát.",
      "clarification_cs": "- Malý meteor, který se odrazí, se počítá jako zásah, takže pak už znovu házet nemusíte.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Pas de chance",
      "text_fr": "Lorsque vous résolvez l'impact d'un astéroide ou d'un tir de canon, si personne n'est touché ou n'est obligé d'utiliser une cellule d'énergie, relancez les dés. Si personne ne subit d'impact à nouveau, répétez l'opération (jusqu'à 3 lancers en tout).",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "厄日",
      "text_jp": "もしも流星やレーザー砲撃のコースを決めるダイスを振った際に、【直撃を受けるか、または、バッテリーの使用を強いられる】プレイヤーが1人もいない場合は、ダイスを振りなおす（合計で最大3回まで）。",
      "clarification_jp": "- 跳ね返された流星（小）は「直撃した」ものと扱い、振りなおしは発生しない。",
      "future_jp": null,
      "name_ko": "불운",
      "text_ko": "유성이나 대포의 주사위가 아무도 타격하지 않거나 배터리를 사용하게 하지 않으면, 주사위를 3번까지 다시 굴립니다.",
      "clarification_ko": "- 튕겨 나온 작은 유성은 타격한 것으로 간주하여, 다시 주사위를 굴리지 않습니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Не везёт так не везёт",
      "text_ru": "Если метеорит или выстрел пролетает мимо всех дальнобойщиков (и даже не попадает в щиты), перебросьте оба кубика (до трёх раз).",
      "clarification_ru": "- Если малый метеорит попал в кого-то, но отскочил, перебрасывать кубики не нужно.",
      "future_ru": null
    },
    "nasty_surprise": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Nasty Surprise",
      "text_en": "After building, but before preparing your ship, draw a card to replace this one. (If the replacement is a construction card denoted by [ship icon], draw a different replacement.)",
      "clarification_en": "- After building, discard this card by hitting the [x] button, and hit the [+] button to reveal another.\n- If you find one with a ship icon, keep searching until you find one without it.\n- Enjoy your surprise :)",
      "future text (for expansion stuff)": null,
      "name_de": "Üble Überraschung",
      "text_de": "Nach dem Bau, jedoch vor der Vorbereitung deines Schiffs, ziehst du eine Karte, die diese hier ersetzt. (Falls die Ersatzkarte eine durch [ship icon] gekennzeichnete Baukarte ist, ziehe einen neuen Ersatz.)",
      "clarification_de": "Nach dem Bau, jedoch vor der Vorbereitung deines Schiffs, ziehst du eine Karte, die diese hier ersetzt. (Falls die Ersatzkarte eine durch [ship icon] gekennzeichnete Baukarte ist, ziehe einen neuen Ersatz.)",
      "future_de": null,
      "name_cs": "Nepříjemné překvapení",
      "text_cs": "Poté, co dostavíte, ale před přípravou lodí nahraďte tuto kartu jinou náhodnou. (Pokud je zvolená karta konstrukční, označené [ship icon], lízněte jinou.)",
      "clarification_cs": "- Po dostavění odstraňte tuto kartu kliknutím na [x]. Novou kartu otočte tlačítkem [+].\n- Otáčejte tak dlouho, než najdete kartu než ikony lodi.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Mauvaise surprise",
      "text_fr": "Après avoir construit, mais avant de préparer le lancement, piochez une carte pour remplacer celle-ci. (Si la carte de remplacement piochée est une carte Construction, indiquée par [ship icon], piochez-en une autre.)",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "最悪のサプライズ",
      "text_jp": "建造の終了後、発進の準備をする前に、カード1枚を引いてこのカードと置き換える。（もしも代わりが宇宙船アイコン [ship icon] のある建造系カードだった場合は、さらに別なカードを引く）。",
      "clarification_jp": "- 建造の終了後、 [x] ボタンをクリックしてこのカードを捨て札とし、 [+] ボタンをクリックして別のカードを公開する。\n - カードに宇宙船アイコンがある場合は、表記の無いカードが出るまで引き続ける。\n - サプライズを楽しもう :)",
      "future_jp": null,
      "name_ko": "심술궂은 서프라이즈",
      "text_ko": "우주선을 완성한 다음, 우주선을 준비하기 전에 이 카드를 대체할 카드를 뽑습니다. (대체할 카드가 [ship icon]이면 다른 교체 카드를 뽑습니다.)",
      "clarification_ko": "- 우주선을 완성한 다음, [x] 버튼을 눌러서 카드를 버리고, [+] 버튼을 누르면 다른 카드가 공개됩니다.\n- 우주선 아이콘이 있는 카드가 나오면, 우주선 아이콘이 없는 카드가 나올 때까지 계속합니다.\n- 당신을 위한 서프라이즈를 확인하세요.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Неприятный сюрприз",
      "text_ru": "Когда все завершили постройку кораблей, замените эту карту другой! Если новая карта помечена символом [ship icon], также замените её.",
      "clarification_ru": "- Когда все завершили постройку кораблей, нажмите на кнопку [x] на этой карте и откройте новую, нажав [+] слева.\n- Если на новой карте — символ правила постройки, также замените её (см. выше).\n- Вот он, ваш сюрприз! :)",
      "future_ru": null
    },
    "infected_goods": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Infected Goods",
      "text_en": "When loading goods, if the number of goods depicted exceeds the number of aliens you have aboard, you lose 1 human astronaut for each extra block (even if you don’t load them all).",
      "clarification_en": "- For example, if you have 1 alien and land on a planet that offers 3 goods, you load as many goods as you want, but then lose 2 humans.",
      "future text (for expansion stuff)": null,
      "name_de": "Infizierte Güter",
      "text_de": "Übersteigt beim Laden von Gütern die Anzahl der angezeigten Güter die Anzahl der Aliens an Bord deines Schiffs, verlierst du 1 menschlichen Astronaut pro überzähligem Block (sogar, wenn du nicht alle Güter lädst).",
      "clarification_de": "Übersteigt beim Laden von Gütern die Anzahl der angezeigten Güter die Anzahl der Aliens an Bord deines Schiffs, verlierst du 1 menschlichen Astronaut pro überzähligem Block (sogar, wenn du nicht alle Güter lädst).",
      "future_de": null,
      "name_cs": "Infikované zboží",
      "text_cs": "Pokud při nakládání převyšuje počet zobrazeného zboží počet vašich mimozemšťanů, ztrácíte 1 kosmonauta za každou kostičku navíc (dokonce i když je všechny nenaložíte).",
      "clarification_cs": "- Např. pokud máte 1 mimozemšťana a přistanete na planetě se 3 kostičkami zboží, můžete naložit, kolik chcete, ale každopádně ztratíte 2 kosmonauty.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Marchandises contaminées",
      "text_fr": "Lors d'un chargement de marchandises, si le nombre de marchandises indiqué est supérieur au nombre d'extraterrestres que vous avez à bord, perdez 1 astronaute par cube en excès (même si vous ne les chargez pas tous).",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "汚染された商品",
      "text_jp": "商品を積み込む際、もしも表記された商品の個数が自分の宇宙船に乗っている異星人の数よりも多い場合は、超過分のブロック1個につき地球人宇宙飛行士1人を失う（たとえ全ての商品を積み込まなくても）。",
      "clarification_jp": "- 例えば、あなたの宇宙船に異星人1人が居て、商品3個が描かれた惑星に着陸した場合、あなたは商品を望む個数積み込めるが、いずれにせよ地球人2人を失う。",
      "future_jp": null,
      "name_ko": "감염된 상품",
      "text_ko": "상품을 실을 때, 표시된 상품의 수가 탑승한 외계인 수보다 많으면, (상품을 다 싣지 않더라도) 초과 상품당 인간 승무원 1명을 잃습니다.",
      "clarification_ko": "- 예를 들어, 외계인 하나가 있는데 상품 3개를 제공하는 행성에 착륙하면, 상품은 원하는 대로 선적할 수 있지만, 그 후에 인간 승무원 2명을 잃습니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Заражённые товары",
      "text_ru": "Когда вы грузите товары на корабль, вы теряете по 1 космонавту за каждый товар, доступный для погрузки (даже если вы не будете брать их все). Если на корабле есть инопланетяне, вы теряете на 1 космонавта меньше за каждого из них: у инопланетян иммунитет.",
      "clarification_ru": "- Например: у вас в экипаже есть 1 инопланетянин. Если вы приземлитесь на планету, на которой есть 3 товара, и погрузите хотя бы один, вы потеряете 2 космонавтов.",
      "future_ru": null
    },
    "defective_connectors": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": "Y",
      "name_en": "Defective Connectors",
      "text_en": "When determining engine strength, subtract 1 for every universal connector joined to a one-pipe or two-pipe connector. You can reduce this penalty by removing any number of components connected this way. (They fall off.)",
      "clarification_en": "- In a Combat Zone, all players with negative engine strength are considered to be tied at 0.",
      "future text (for expansion stuff)": null,
      "name_de": "Angeknackste Anschlüsse",
      "text_de": "Beim Ermitteln der Antriebsstärke musst du 1 pro Universalanschluss abziehen, der mit einem Ein- oder Zwei-Rohr-Anschluss verbunden ist. Du kannst diese Strafe reduzieren, indem du beliebig viele derart angeschlossene Bauteile entfernst. (Diese fallen ab.)",
      "clarification_de": "Beim Ermitteln der Antriebsstärke musst du 1 pro Universalanschluss abziehen, der mit einem Ein- oder Zwei-Rohr-Anschluss verbunden ist. Du kannst diese Strafe reduzieren, indem du beliebig viele derart angeschlossene Bauteile entfernst. (Diese fallen ab.)",
      "future_de": null,
      "name_cs": "Poškozené přípojky",
      "text_cs": "Když určujete sílu motorů, odečtěte 1 za každou univerzální přípojku napojenou na jednoduchou nebo dvojitou přípojku. Tento postih můžete snížit tím, že odstraníte libovolný počet dílků z lodi (odpadnou).",
      "clarification_cs": "- V Bojové zóně se všichni hráči s negativní silou motorů počítají, jako by remizovali s 0.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Connecteurs défectueux",
      "text_fr": "Lorsque vous déterminez la puissance de vos moteurs, réduisez votre total de 1 pour chaque connecteur universel relié à un connecteur simple ou double. Vous pouvez réduire cette pénalité en retirant n'importe quel nombre de composants reliés ainsi (ils tombent du vaisseau).",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "不良品コネクタ",
      "text_jp": "エンジンのパワーを計算する際、【パイプ1本または2本いずれかのコネクタに接続している共通コネクタ】1個につきパワーが1減少する。あなたは対象のパーツをいくつでも取り除いてこのペナルティを減らしてよい。（そのパーツは落下する）。",
      "clarification_jp": "- 《交戦宙域》で、エンジンのパワーがマイナスのプレイヤーは全員、パワー’0’と同点と扱う。",
      "future_jp": null,
      "name_ko": "결함있는 연결 장치",
      "text_ko": "엔진 출력을 정할 때, 범용 연결 장치에 연결된 1관 또는 2관 연결 장치당 1을 뺍니다. 원하는 부품을 제거하여 빼는 값을 줄일 수 있습니다. 제거한 부품은 분리됩니다.",
      "clarification_ko": "- 교전 지대에서, 엔진 출력이 음수인 모든 플레이어는 0으로 간주합니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Несостыковки",
      "text_ru": "Когда нужно определить мощность двигателей, отнимите 1 за каждый универсальный разъём, соединённый не с универсальным разъёмом. Вы можете отсоединить любое число модулей, соединённых таким образом (они отвалятся!), чтобы это исправить.",
      "clarification_ru": "- В зоне конфликта отрицательная мощность двигателей считается равной 0.",
      "future_ru": null
    },
    "space_junk": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Space Junk",
      "text_en": "After each adventure, all components that fell off of any ship act as large meteors from the front for all following ships.",
      "clarification_en": "- Components hit by meteors or cannon fire are destroyed, and do not become space junk. This effect applies only to components which fall off. (Usually this is because the component holding them on to the ship was destroyed.)\n- During the adventure, keep components that fall off in a separate pile.\n- At the end of the adventure, in flight order, evaluate each player’s pile; for each component, roll 1 large meteor that affects all players behind.\n- Components that fall off while resolving the Space Junk effect also become large meteors for all ships behind.",
      "future text (for expansion stuff)": null,
      "name_de": "Weltraumschrott",
      "text_de": "Nach jedem Abenteuer werden alle Bauteile, die von allen Schiffen abgefallen sind, für alle nachfolgenden Schiffe zu großen Meteoriten von vorn.",
      "clarification_de": "Nach jedem Abenteuer werden alle Bauteile, die von allen Schiffen abgefallen sind, für alle nachfolgenden Schiffe zu großen Meteoriten von vorn.",
      "future_de": null,
      "name_cs": "Vesmírný odpad",
      "text_cs": "Po vyhodnocení každé karty se všechny dílky, které kvůli ní odpadly, chovají jako velké meteory a ohrožují všechny lodě za sebou.",
      "clarification_cs": "- Dílky zasažené meteory nebo střelami jsou zničené a nestávají se odpadem. To se týká pouze odpadlých dílků (většinou těch, které odpadly spolu s nějakým zničeným dílkem).\n- Během vyhodnocování karty střádejte odpadlé dílky na zvláštní hromádku.\n- Po vyhodnocení karty pak projděte hromádky hráčů podle pořadí. Každý dílek se stává velkým meteorem, který míří na všechny lodě za daným hráčem.\n- Dílky, které odpadnou při vyhodnocování Vesmírného odpadu, se také stávají velkými meteory.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Déchets spatiaux",
      "text_fr": "Après chaque aventure, tous les composants tombés d'un vaisseau sont considérés comme de gros astéroïdes venant de l'avant pour tous les vaisseaux suivants.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "宇宙ゴミ",
      "text_jp": "各アドベンチャーの解決後、宇宙船から落下した全てのパーツは、後続の宇宙船全てに対する【前方から飛来する流星（大）】として扱う。",
      "clarification_jp": "- 流星やレーザー砲撃の直撃を受けたパーツは破壊されるため《宇宙ゴミ》にはならない。この効果は落下したパーツにのみ適用される。（通常、宇宙船とつながる間のパーツが破壊されて、その先のパーツが落下する）。\n - アドベンチャーの解決中、落下したパーツは別のタイル山に分けておく。\n - アドベンチャーの解決後、「順番に」各プレイヤーのタイル山をチェックする； 各パーツごとに、より後ろを飛ぶプレイヤー全員に対する流星（大）としてダイスを振る。\n - 《宇宙ゴミ》の効果を解決中に落下したパーツもまた、後続の宇宙船全てに対する流星（大）になる。",
      "future_jp": null,
      "name_ko": "우주 쓰레기",
      "text_ko": "모험 카드의 실행이 끝날 때마다, 우주선에서 분리된 모든 부품은 뒤따르는 모든 우주선의 정면에서 오는 큰 유성처럼 작용합니다.",
      "clarification_ko": "- 유성이나 대포 사격에 맞은 부품은 파괴되며, 우주 쓰레기가 되지 않습니다. 이 효과는 분리된 부품에만 적용됩니다. (보통 우주선에 부착된 부품이 파괴되었기 때문입니다.)\n- 해당 모험을 실행하는 동안 분리된 부품을 따로 더미를 만들어 놓습니다.\n- 모험이 끝날 때, 비행 순서로 각 플레이어의 더미를 확인합니다. 부품마다 큰 유성이 되어 주사위를 굴려서, 뒤에 있는 모든 플레이어에게 영향을 미칩니다.\n- 우주 쓰레기 효과를 실행하는 동안 분리된 부품도 뒤에 있는 모든 플레이어에게는 큰 유성이 됩니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Космический мусор",
      "text_ru": "После каждого происшествия модули, отвалившиеся от летящих впереди кораблей, становятся большими метеоритами для летящих позади. Эти метеориты прилетают спереди.",
      "clarification_ru": "- Если модуль был уничтожен (метеоритом или выстрелом), это не считается. Модуль должен именно отвалиться от корабля.\n- Отложите все отвалившиеся модули, пока происшествие не закончится.\n- Затем летящий первым считает, сколько у него отвалившихся модулей: все игроки позади сталкиваются с ними. Затем проделайте то же самое для 2-го игрока и так далее.\n- Если из-за космического мусора от корабля отвалились модули, они сразу становятся космическим мусором для летящих позади.",
      "future_ru": null
    },
    "sommersault": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": "Y",
      "name_en": "Gravitational Anomaly",
      "text_en": "During building, engines can point backward or forward. Engines pointing forward do not count when determining engine strength. After each Open Space or Planet adventure, rotate your ship 180 degrees.",
      "clarification_en": null,
      "future text (for expansion stuff)": null,
      "name_de": "Gravitationsanomalie",
      "text_de": "Beim Bau dürfen Antriebe nach hinten oder vorne zeigen. Nach vorn zeigende Antriebe zählen beim Ermitteln der Antriebsstärke nicht mit. Nach jedem Freier-Weltraum- oder Planeten-Abenteuer drehst du dein Schiff um 180 Grad.",
      "clarification_de": null,
      "future_de": null,
      "name_cs": "Gravitační anomálie",
      "text_cs": "Během stavby mohou motory mířit dozadu i dopředu. Motory mířící dopředu se nepočítají, když určujete sílu motorů. Po každé kartě Volný vesmír nebo Planety otočte svou loď o 180°.",
      "clarification_cs": null,
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Anomalie gravitationnelle",
      "text_fr": "Au cours de l'assemblage, les moteurs peuvent pointer vers l'avant et vers l'arrière. Les moteurs pointant vers l'avant sont ignorés lorsque vous déterminez la puissance de vos moteurs. Après chaque aventure Espace intersidéral ou Planètes, faites pivoter votre vaisseau de 180 degrés.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "重力異常",
      "text_jp": "建造中、エンジンは後方または前方に向けてよい。エンジンのパワーを計算する際、前方を向いたエンジンは数えない。アドベンチャー《宇宙空間》または《惑星》が終了するたび、プレイヤーは宇宙船を上下180°回転させる。",
      "clarification_jp": null,
      "future_jp": null,
      "name_ko": "중력 이상 현상",
      "text_ko": "우주선을 만드는 동안, 엔진이 뒤쪽이나 앞쪽을 향할 수 있습니다. 엔진 출력을 결정할 때, 앞쪽을 향한 엔진은 포함되지 않습니다. 탁 트인 지대나 행성 모험 카드를 실행한 다음, 배를 180도 회전시킵니다.",
      "clarification_ko": null,
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Гравитационная аномалия",
      "text_ru": "Во время постройки кораблей двигатели могут быть направлены не только назад, но и вперёд. Двигатели, направленные вперёд, не учитываются при подсчёте мощности. После каждого происшествия «Открытый космос» или «Планета» разворачивайте свой корабль на 180 градусов.",
      "clarification_ru": null,
      "future_ru": null
    },
    "dead_zone": {
      "pic_status": "F",
      "app_status": null,
      "translate": null,
      "ship_icon": "Y",
      "name_en": "Dead Zone",
      "text_en": "Before building, roll to determine a column. (If the column is outside the ship’s squares, roll again until you hit). All components in this column are non-functional.",
      "clarification_en": "- Nothing works in that column. Components there can hold no crew, batteries, or goods. Alien life support systems do not support connected cabins. Engines and cannons do not count toward your strength.\n- However, all components still must follow the usual ship-building rules.",
      "future text (for expansion stuff)": "- V tomto sloupci nic nefunguje. Dílky nemohou obsahovat posádku, baterie ani zboží. Podpora životních funkcí nepodporuje. Děla a motory se nepočítají při výpočtu síly.\n- Všechny dílky stále musí odpovídat pravidlům pro stavbu.\n- Nezničitelné plátování se považuje za strukturální součást lodi (jako přípojky), takže funguje jako normálně.",
      "name_de": "Tote Zone",
      "text_de": "Vor dem Bau erwürfelt ihr eine Spalte. (Sollte sie außerhalb der Felder eurer Schiffe liegen, würfelt erneut, bis ihr eine Spalte trefft, in der mindestens ein Schiff Bauteile hat.) Alle Bauteile in dieser Spalte haben keine Funktion.",
      "clarification_de": "Vor dem Bau erwürfelt ihr eine Spalte. (Sollte sie außerhalb der Felder eurer Schiffe liegen, würfelt erneut, bis ihr eine Spalte trefft, in der mindestens ein Schiff Bauteile hat.) Alle Bauteile in dieser Spalte haben keine Funktion.",
      "future_de": null,
      "name_cs": "Mrtvá zóna",
      "text_cs": "Před stavbou hoďte kostkami a určete sloupec. (Házejte tak dlouho, než se trefíte do oblasti lodi.) Všechny dílky v tomto sloupci budou nefunkční.",
      "clarification_cs": "- V tomto sloupci nic nefunguje. Dílky nemohou obsahovat posádku, baterie ani zboží. Podpora životních funkcí nepodporuje. Děla a motory se nepočítají při výpočtu síly.\n- Všechny dílky stále musí odpovídat pravidlům pro stavbu.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Zone blanche",
      "text_fr": "Avant l'assemblage, lancez les dés pour déterminer une colonne (si cette colonne est en dehors du vaisseau, relancez les dés jusqu'à obtenir une colonne valide). Tous les composants de cette colonne sont inactifs.",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "作動不能ゾーン",
      "text_jp": "建造の開始前、ダイス2個を振り縦列1列を決める。（もしも宇宙船の建造エリア外になったら、エリア内が出るまで振りなおす）。その縦列に配置された全てのパーツは機能停止する。",
      "clarification_jp": "- この縦列では何も作動しない。ここにあるパーツには乗組員、バッテリー、商品を一切配置できない。異星人用の《生命維持システム》は船室に接続しても効果が無い。エンジンとレーザー砲はパワーを計算する際に加算されない。\n - それでも、全てのパーツは通常どおり宇宙船建造のルールに従う必要がある。",
      "future_jp": "この縦列では何も作動しない。ここにあるパーツには乗組員、バッテリー、商品を一切配置できない。異星人用の《生命維持システム》は船室に接続しても効果が無い。エンジンとレーザー砲はパワーを計算する際に加算されない。\n それでも、全てのパーツは通常どおり宇宙船建造のルールに従う必要がある。\n 極硬鋼装甲板（外装面）は（コネクタと同様に）宇宙船の構造部品として扱うため、通常どおり機能する。",
      "name_ko": "작동 불가 지대",
      "text_ko": "우주선을 만들기 전에, 주사위를 굴려서 세로줄 하나를 정합니다. 해당 세로줄이 우주선의 범위를 벗어나면 다시 굴립니다. 그 세로줄에 있는 모든 부품은 작동하지 않습니다.",
      "clarification_ko": "- 해당 세로줄은 아무것도 작동하지 않습니다. 승무원, 배터리, 상품 등, 아무것도 실을 수 없습니다. 외계인 생명 유지 장치는 연결된 선실을 지원하지 않습니다. 엔진과 대포는 우주선의 출력과 화력에 힘을 더하지 않습니다.\n- 그러나, 모든 부품은 여전히 우주선 건설 규칙을 따라야 합니다.",
      "future_ko": "해당 세로줄은 아무것도 작동하지 않습니다. 승무원, 배터리 토큰, 상품 등, 어떤 것도 실을 수 없습니다. 외계인 생명 유지 장치는 연결된 선실을 지원하지 않습니다. 엔진과 대포는 우주선의 출력과 화력에 힘을 더하지 않습니다. \n그러나, 모든 부품은 여전히 우주선 건설 규칙을 따라야 합니다.\n연결 장치처럼 해당 부품의 기능을 상실할 수 없는 부분은 우주선의 구조 모듈로 간주하여, 정상적으로 작동합니다.",
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Мёртвая зона",
      "text_ru": "Перед постройкой кораблей бросьте кубики, чтобы определить столбец на планшетах кораблей (если в столбце нет ячеек, перебросьте кубики, пока не выпадет столбец с ячейками). Все модули в ячейках этого столбца не функционируют.",
      "clarification_ru": "- Модули в столбце мёртвой зоны считаются структурными модулями. Двигатели и пушки не дают мощности, батарейные модули пустуют, трюмы непригодны для товаров, каюты — для жизни, жизнеобеспечение ломается. Но все разъёмы работают как обычно.\n- Вы обязаны соблюдать все правила постройки и ориентации модулей даже в столбце мёртвой зоны.",
      "future_ru": "Модули в столбце мёртвой зоны считаются структурными модулями.\nДвигатели и пушки не дают мощности, батарейные модули пустуют, трюмы непригодны для товаров, каюты — для жизни, жизнеобеспечение ломается. Но все разъёмы работают как обычно.\nВы обязаны соблюдать все правила постройки и ориентации модулей даже в столбце мёртвой зоны."
    },
    "abandoned_debris": {
      "pic_status": "a",
      "app_status": null,
      "translate": null,
      "ship_icon": null,
      "name_en": "Abandoned Debris",
      "text_en": "At the start of an Abandoned Ship or Abandoned Station adventure, each player, in flight order, votes for a direction. All ships face a large meteor from the direction with the most votes (or from all tied directions).",
      "clarification_en": "- In a tie, evaluate meteors from all tied directions in the order in which they got their first vote.",
      "future text (for expansion stuff)": null,
      "name_de": "Trümmerteile",
      "text_de": "Wenn eine Karte Verlassene Station oder Verlassenes Schiff aufgedeckt wird, stimmen alle Spieler (in Flugreihenfolge) für eine Richtung. Alle Schiffe werden von einem großen Meteoriten aus der Richtung mit den meisten Stimmen getroffen (oder bei Gleichstand aus allen diesen Richtungen).",
      "clarification_de": "Wenn eine Karte Verlassene Station oder Verlassenes Schiff aufgedeckt wird, stimmen alle Spieler (in Flugreihenfolge) für eine Richtung. Alle Schiffe werden von einem großen Meteoriten aus der Richtung mit den meisten Stimmen getroffen (oder bei Gleichstand aus allen diesen Richtungen).",
      "future_de": null,
      "name_cs": "Opuštěné trosky",
      "text_cs": "Když otočíte Opuštěnou loď nebo stanici, všichni hráči (v pořadí) budou hlasovat o směru. Všechny lodě musí čelit velkému meteoru ze směru s nejvíce hlasy (nebo ze všech remizovaných směrů).",
      "clarification_cs": "- V případě remízy letí meteory ze všech těchto směrů, počínaje směrem, který dostal první hlas.",
      "name_es": null,
      "text_es": null,
      "clarification_es": null,
      "future_es": null,
      "name_fr": "Débris abandonnés",
      "text_fr": "Lorsqu'une carte Vaisseau abandonné ou Station abandonnée est révélée, tous les joueurs (dans l'ordre) votent pour une direction. Tous les vaisseaux doivent faire face à un gros astéroïde venant de la direction ayant reçu le plus de votes (ou de toutes les directions à égalité).",
      "clarification_fr": null,
      "future_fr": null,
      "name_it": null,
      "text_it": null,
      "clarification_it": null,
      "future_it": null,
      "name_jp": "放置されたデブリ",
      "text_jp": "《廃棄された宇宙船》または《廃棄されたステーション》カードが公開された場合、プレイヤー全員は「順番に」上下左右いずれかの方向に投票する。全ての宇宙船は、最も票の多い方向から（同点の場合は、同点の方向全てから）流星（大）の直撃を受ける。",
      "clarification_jp": "- 同点の場合は、同点の方向全てから、最初に票が入った順番で流星を処理していく。",
      "future_jp": null,
      "name_ko": "버려진 잔해",
      "text_ko": "버려진 우주선 또는 버려진 정거장 카드가 공개되면 모든 플레이어가 비행 순서대로 방향을 투표합니다. 가장 많은 표를 얻은 방향(동수이면 모두)에서 오는 큰 유성 하나를 모든 우주선에 적용합니다.",
      "clarification_ko": "- 가장 많은 표를 얻은 방향이 동수면 먼저 투표한 순서대로 모든 동수 방향에 대해 큰 유성 효과를 실행합니다.",
      "future_ko": null,
      "name_pl": null,
      "text_pl": null,
      "clarification_pl": null,
      "future_pl": null,
      "name_ro": null,
      "text_ro": null,
      "clarification_ro": null,
      "future_ro": null,
      "name_ru": "Облака обломков",
      "text_ru": "Когда игроки сталкиваются с заброшенной станцией или заброшенным кораблём, перед этим все по очереди (начиная с лидера) выбирают направление — спереди, слева, справа или сзади. Затем все немедленно сталкиваются с метеоритом, летящим со стороны, получившей большинство голосов (если таких несколько, то по одному с каждой из них).",
      "clarification_ru": "- Если таких метеоритов несколько, первым прилетает метеорит, за который проголосовали первым, и далее в порядке очерёдности.",
      "future_ru": null
    }
  },
  "Texts": {
    "title": {
      "string_en": "Welcome to Rough Roads",
      "string_de": "Willkommen zu Krasse Strecken",
      "string_cs": "Vítejte na Drsných štrekách!",
      "string_es": null,
      "string_fr": "Bienvenue sur les Routes chaotiques",
      "string_it": null,
      "string_jp": "ようこそ『ラフ・ロード』へ",
      "string_ko": "고된 여정에 오신 것을 환영합니다.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Ухабистый космос ждёт!"
    },
    "subtitle": {
      "string_en": "an expansion for the Galaxy Trucker board game",
      "string_de": "eine Erweiterung des Brettspiels Galaxy Trucker",
      "string_cs": "rozšíření k deskové hře Galaxy Trucker",
      "string_es": null,
      "string_fr": "Une extension pour le jeu de plateau Galaxy Trucker",
      "string_it": null,
      "string_jp": "『ギャラクシートラッカー』ボードゲーム用拡張セット",
      "string_ko": "갤럭시 트러커 보드게임 확장",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Дополнение для настольной игры «Космические дальнобойщики»"
    },
    "": {
      "string_en": null,
      "string_de": null,
      "string_cs": null,
      "string_es": null,
      "string_fr": null,
      "string_it": null,
      "string_jp": null,
      "string_ko": null,
      "string_pl": null,
      "string_ro": null,
      "string_ru": null
    },
    "paragraph1": {
      "string_en": "This app represents a deck of Rough Road cards. You can do the stuff you could do with a regular deck: reveal a card with the [+] button, discard a card with the [x] button, etc. You can check the discard pile by clicking the icon on the bottom left.",
      "string_de": "Die App liefert ein Deck der Krasse-Strecken-Karten. Du kannst damit das machen, was auch bei einem normalen Deck geht: eine Karte durch den [+]-Button aufdecken, eine Karte durch den [x]-Button abwerfen usw. Du kannst den Abwurfstapel durchsuchen, indem du das Icon links unten anklickst.",
      "string_cs": "Tato aplikace obsahuje balíček karet Drsných štrek. Chová se obdobně jako fyzický balíček – karty otáčíte tlačítkem [+], odhazujete tlačítkem [x] atd. Odhazovací balíček si můžete prohlédnout stisknutím ikony vlevo dole.",
      "string_es": null,
      "string_fr": "Cette application consiste en un paquet de cartes Routes chaotiques. Vous pouvez faire tout ce que vous feriez avec un paquet de cartes normal : révéler une carte en cliquant sur [+], défausser une carte en cliquant sur [x], etc. Vous pouvez consulter la défausse en cliquant sur l'icône en bas à gauche.",
      "string_it": null,
      "string_jp": "このアプリは『ラフ・ロード』カードのデッキを表している。通常のデッキで可能な処理が、これでできる： [+] ボタンでカード1枚を公開、 [x] ボタンでカード1枚を捨て札に、等々。左下角のアイコンをクリックして捨て札山をチェックできる。",
      "string_ko": "이 앱은 고된 여정 확장 카드입니다. 일반 카드 더미로 할 수 있는 것들을 할 수 있습니다. [+] 버튼을 눌러서 카드 한 장을 공개하거나, [x] 버튼을 눌러서 카드 한 장을 버리는 등의 작업을 할 수 있습니다. 왼쪽 하단의 아이콘을 클릭하면 버리는 카드 더미를 확인할 수 있습니다.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Это цифровая колода карт ухабистого космоса. Чтобы взять новую карту, нажмите [+]. Чтобы сбросить карту, нажмите [x]. Чтобы посмотреть на открытую карту, нажмите на неё. Чтобы посмотреть карты в сбросе, нажимайте на красный значок слева внизу."
    },
    "paragraph2": {
      "string_en": "Agree on the difficulty: 1 – hard, 2 – extreme, 3 – insane. Before each flight, reveal that many cards. Read them out loud – they contain special rules for that flight. Keep your device nearby, so players can check the cards at any time. Some cards may have rules clarifications [i].",
      "string_de": "Lege einen Schwierigkeitsgrad fest: 1 – hart, 2 – extrem, 3 – wahnsinnig. Vor jedem Flug deckst du so viele Karte auf. Lies sie laut vor – sie beschreiben besondere Regeln für diesen Flug. Lass das Gerät mit der App in Griffweite, damit alle die Karten jederzeit checken können. Zu einigen Karten gibt es Regelerklärungen [i].",
      "string_cs": "Domluvte se na obtížnosti: 1 = těžká, 2 = extrémní, 3 = šílená. Před každým letem pak otočte tolik karet. Nahlas je přečtěte, jsou na nich popsaná speciální pravidla pro let. Zařízení pak nechte v dosahu, aby si kdokoliv mohl pravidla později připomenout. Některé z karet mají vysvětlivky [i].",
      "string_es": null,
      "string_fr": "Mettez-vous d'accord sur le niveau de difficulté : 1 - Difficile, 2 - Extrême, 3 - Insensé. Avant chaque vol, révélez autant de cartes que le niveau de difficulté choisi. Lisez les cartes à voix haute : elles indiquent des règles spécifiques à ce vol. Conservez votre tablette ou téléphone à proximité afin que les joueurs puissent consulter ces cartes à tout moment. Certaines cartes disposent de précisions de règles (en cliquant sur [i]).",
      "string_it": null,
      "string_jp": "全員で難易度を決める： 1 – 困難、2 – 過激、3 – 常識外れ。各航海の前に、指定された枚数のカードを公開する。カードの内容を読み上げる – カードにはこの航海専用のルールが記載されている。プレイヤー全員が何時でもカード内容をチェックできるよう、デバイスを手近に置いておく。カードによっては [i] からルールの補足説明が参照できる。",
      "string_ko": "난이도를 정하세요: 1 - 어려움, 2 - 매우 어려움, 3 - 미치게 어려움. 각 비행을 시작하기 전에, 선택한 난이도만큼 카드를 공개합니다. 내용을 소리 내어 읽습니다. 각 카드는 해당 비행에 적용할 특수 규칙이 표시되어 있습니다. 플레이어들이 언제든지 카드의 내용을 확인할 수 있도록 기기를 근처에 두세요. 일부 카드는 좀 더 자세한 규칙이 설명된 정보가 포함되어 있습니다 [i].",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Перед началом игры выберите уровень ухабистости космоса: 1 (сложный), 2 (очень сложный) или 3 (кошмарный) — и откройте столько же карт. На каждой открытой карте есть новое правило, которое всем придётся соблюдать до конца полёта. Прочтите текст карты вслух. Держите ваше устройство поблизости, чтобы все могли в любой момент свериться с картами. К некоторым картам есть пояснения: чтобы их прочесть, нажмите [i]."
    },
    "paragraph3": {
      "string_en": "After the flight, discard the cards. The app remembers your discard pile, so you will face different cards next time. Or you can choose to shuffle the discard pile back into the deck.",
      "string_de": "Nach dem Flug wirfst du die Karten ab. Die App merkt sich den Abwurfstapel, daher wird es beim nächsten Mal andere Karten geben. Du kannst aber auch wählen, den Abwurfstapel wieder ins Deck zu mischen.",
      "string_cs": "Po letu karty odhoďte. Aplikace si pamatuje odhozené karty, takže příště vám vybere jiné. Nebo můžete balíček zamíchat a znovu vybírat náhodně.",
      "string_es": null,
      "string_fr": "Après le vol, défaussez les cartes. L'application se souvient de votre défausse, vous assurant de rencontrer des cartes différentes à chaque partie. Vous pouvez bien entendu décider de mélangez la défausse à la pioche.",
      "string_it": null,
      "string_jp": "航海の終了後、カードを全て捨て札とする。アプリにはあなたの捨て札山が記録されているため、次の回は異なるカードが引かれる。または、捨て札山をデッキに戻してシャッフルする選択もできる。",
      "string_ko": "비행이 끝나면 카드를 버립니다. 이 앱은 여러분이 버린 카드 더미를 기록하기 때문에, 다음번에는 다른 카드를 만나보실 수 있습니다. 원하시면 버린 카드 더미를 뽑는 카드 더미에 섞을 수 있습니다.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "После полёта сбросьте все карты ухабистого космоса. Приложение сохраняет все карты, которые вы открыли или сбросили: в следующем полёте вы возьмёте новые. В любой момент вы можете замешать карты из сброса в колоду, нажав на соответствующую кнопку."
    },
    "footnote": {
      "string_en": "Important: Do not use this expansion with new players. Lower the difficulty if someone chickens out. [random_extra_hint]. Have fun!",
      "string_de": "Wichtig: Benutze diese Erweiterung niemals mit Neulingen. Senke den Schwierigkeitsgrad, falls jemand kneifen will. [random_extra_hint]. Habt Spaß!",
      "string_cs": "Důležité: Nehrajte toto rozšíření s novými hráči. Pokud se někdo bojí, snižte obtížnost. [random_extra_hint]. Příjemnou zábavu!",
      "string_es": null,
      "string_fr": "Important : Évitez d'utiliser cette extension avec des joueurs débutants. Diminuez la difficulté si un joueur fait sa poule mouillée. [random_extra_hint]. Amusez-vous bien !",
      "string_it": null,
      "string_jp": "重要： 初心者プレイヤーにはこの拡張を使用しないで。誰か尻込みする場合は難易度を下げよう。[random_extra_hint]。楽しい旅を！",
      "string_ko": "중요합니다: 이 게임을 처음 하는 분들과 게임을 하실 때는 이 확장을 사용하지 마십시오. [random_extra_hint]. 즐거운 비행 되세요!",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Важно! Не для новичков и неопытных дальнобойщиков. Если кто-то сдрейфит, понизьте уровень сложности. [random_extra_hint]. Главное — чтобы всем было весело!"
    },
    "extra_hint0": {
      "string_en": "Do not let kids eat the game pieces",
      "string_de": "Lasst keinesfalls Kinder auf dem Spielmaterial herumkauen",
      "string_cs": "Nedovolte dětem jíst herní komponenty!",
      "string_es": null,
      "string_fr": "Ne laissez pas vos enfants mâcher les figurines.",
      "string_it": null,
      "string_jp": "ゲームの内容物を幼児が口に入れないよう注意",
      "string_ko": "아이들이 게임 구성품을 입에 넣지 못하게 하세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не разрешайте детям есть компоненты игры"
    },
    "extra_hint1": {
      "string_en": "Do not lick the device screen",
      "string_de": "Bitte den Bildschirm nicht ablecken",
      "string_cs": "Neolizujte obrazovku zařízení!",
      "string_es": null,
      "string_fr": "Ne léchez pas votre écran.",
      "string_it": null,
      "string_jp": "デバイスの画面を舐めないこと",
      "string_ko": "기기의 화면을 핥지 마세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не трогайте экран языком"
    },
    "extra_hint2": {
      "string_en": "Do not let any cat walk on the table while playing",
      "string_de": "Katzen sind während des Spiels vom Tisch fernzuhalten",
      "string_cs": "Nedovolte kočkám procházet se při hře po stole!",
      "string_es": null,
      "string_fr": "Tenez le chat hors de portée de la zone de jeu.",
      "string_it": null,
      "string_jp": "プレイ中は猫を近づけないこと",
      "string_ko": "게임을 할 때 고양이가 테이블 위를 걷게 두지 마세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не давайте коту забраться на стол во время игры"
    },
    "extra_hint3": {
      "string_en": "Wash your hands regularly",
      "string_de": "Wasche deine Hände regelmäßig",
      "string_cs": "Pravidelně si myjte ruce!",
      "string_es": null,
      "string_fr": "Lavez-vous les mains régulièrement.",
      "string_it": null,
      "string_jp": "こまめに手を洗おう",
      "string_ko": "규칙적으로 손을 씻으세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Регулярно мойте руки"
    },
    "extra_hint4": {
      "string_en": "Do not use strong language unless your ship completely falls apart",
      "string_de": "Kraftausdrücke sind zu vermeiden, es sei denn, dein Schiff fällt komplett auseinander",
      "string_cs": "Nenadávejte, dokud se vám loď zcela nerozpadne!",
      "string_es": null,
      "string_fr": "Interdiction de jurer, sauf si votre vaisseau est réduit en confetti.",
      "string_it": null,
      "string_jp": "あなたの宇宙船がバラバラにならない限り、下品な言葉は禁止",
      "string_ko": "우주선이 완파되지 않는 한, 너무 심한 말은 하지 마세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не используйте бранные слова, пока ваш корабль окончательно не развалится"
    },
    "extra_hint5": {
      "string_en": "Do not play Galaxy Trucker while driving",
      "string_de": "Galaxy Trucker darf während des Führens eines Fahrzeugs nicht gespielt werden",
      "string_cs": "Nehrajte Galaxy Trucker při řízení!",
      "string_es": null,
      "string_fr": "Ne jouez pas à Galaxy Trucker en conduisant.",
      "string_it": null,
      "string_jp": "運転中のプレイは禁止されています",
      "string_ko": "운전하실 때는 갤럭시 트러커를 하지 마세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не играйте в «Космических дальнобойщиков» за рулём"
    },
    "extra_hint6": {
      "string_en": "Do not flip the table before the game ends",
      "string_de": "Der Tisch darf erst nach dem Ende des Spiels umgeworfen werden",
      "string_cs": "Neshazujte stůl před koncem hry!",
      "string_es": null,
      "string_fr": "Ne retournez pas la table avant la fin de la partie.",
      "string_it": null,
      "string_jp": "ゲーム終了までテーブルはひっくり返さない",
      "string_ko": "게임이 끝나기 전에 테이블을 뒤엎지 마세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не сбрасывайте компоненты со стола (хотя бы до конца игры)"
    },
    "extra_hint7": {
      "string_en": "Do not play insane difficulty with the elderly",
      "string_de": "Der Schwierigkeitsgrad wahnsinnig ist beim Spiel mit Senioren untersagt",
      "string_cs": "Nehrajte na šílenou obtížnost se seniory!",
      "string_es": null,
      "string_fr": "Évitez le mode Insensé avec des personnes âgées.",
      "string_it": null,
      "string_jp": "高齢者との難易度”常識外れ”プレイは禁止",
      "string_ko": "어르신들과 게임을 할 때는 미치게 어려운 난이도를 설정하지 마세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не играйте на кошмарном уровне сложности с бабушками и дедушками"
    },
    "extra_hint8": {
      "string_en": "Watch your surroundings while grabbing tiles",
      "string_de": "Achte beim Greifen nach Bauteilen auf deine Umgebung",
      "string_cs": "Při braní dílků dávejte pozor na své okolí!",
      "string_es": null,
      "string_fr": "Surveillez vos arrières lorsque vous prenez une tuile.",
      "string_it": null,
      "string_jp": "タイルをつかむ際は周りに気をつけること",
      "string_ko": "부품 타일을 집는 동안 주변 기물을 조심하세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Думайте о здоровье других игроков, когда берёте модули со свалки"
    },
    "extra_hint9": {
      "string_en": "Do not close eyes when facing meteors",
      "string_de": "Augen keinesfalls schließen, wenn Meteore im Anflug sind",
      "string_cs": "Když na vás letí meteor, nezavírejte oči!",
      "string_es": null,
      "string_fr": "Face aux astéroïdes, gardez les yeux ouverts.",
      "string_it": null,
      "string_jp": "流星が向かってきたら目を閉じないこと",
      "string_ko": "유성을 만났을 때 눈을 감지 마세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не летите на метеориты с закрытыми глазами"
    },
    "extra_hint10": {
      "string_en": "Do not drink hot coffee on rough roads",
      "string_de": "Beim Befahren krasser Strecken keinen heißen Kaffee zu sich nehmen",
      "string_cs": "Na drsných štrekách nepijte horkou kávu!",
      "string_es": null,
      "string_fr": "Ne consommez pas de boisson chaude sur les routes chaotiques.",
      "string_it": null,
      "string_jp": "悪路飛行中は熱いコーヒーを飲まない",
      "string_ko": "고된 여정에서 뜨거운 커피를 마시지 마세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не пейте кофе на ухабах (даже в космосе)"
    },
    "extra_hint11": {
      "string_en": "Expect trouble",
      "string_de": "Rechne immer mit Ärger",
      "string_cs": "Očekávejte problémy!",
      "string_es": null,
      "string_fr": "Préparez-vous au pire.",
      "string_it": null,
      "string_jp": "トラブルを覚悟せよ",
      "string_ko": "골칫거리가 있을 것을 예상하세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Будьте готовы"
    },
    "extra_hint12": {
      "string_en": "Do not try to cut the deck, especially not with scissors",
      "string_de": "Das Abwerfen von Karten ist nicht wörtlich gemeint",
      "string_cs": "Lízání karet není míněno doslovně!",
      "string_es": null,
      "string_fr": "Ne coupez jamais un paquet de cartes, surtout avec des ciseaux.",
      "string_it": null,
      "string_jp": "このデッキはカットできません（ハサミを出しても無駄）",
      "string_ko": "카드를 찢으려고 하지 마세요. 특히 가위로는요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Не сдвигайте колоду, особенно с края стола (если только вы не кот)"
    },
    "extra_hint13": {
      "string_en": "Watch for potholes",
      "string_de": "Achte auf Schlaglöcher",
      "string_cs": "Dávejte pozor na výmoly!",
      "string_es": null,
      "string_fr": "Gare aux nids-de-poule.",
      "string_it": null,
      "string_jp": "ブラックホールに注意",
      "string_ko": "구덩이를 조심하세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Соблюдайте правила дорожного движения"
    },
    "extra_hint14": {
      "string_en": "Before launch, be sure your hazard lights are in working order",
      "string_de": "Vergewissere dich vor dem Start, dass alle Warnanzeigen korrekt funktionieren",
      "string_cs": "Před startem se ujistěte, že vám fungují výstražná světla!",
      "string_es": null,
      "string_fr": "Avant le décollage, assurez-vous du bon fonctionnement de vos feux de détresse.",
      "string_it": null,
      "string_jp": "発信前に、ハザードランプが正常に機能するか確認すること",
      "string_ko": "비행을 시작하기 전에, 비상등이 제대로 작동하는지 확인하세요.",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Проверьте фары и сигнальные фонари перед взлётом"
    },
    "button_discard": {
      "string_en": "Discard All",
      "string_de": "Alle abwerfen",
      "string_cs": "Odhodit vše",
      "string_es": null,
      "string_fr": "Défausser tout",
      "string_it": null,
      "string_jp": "全て捨て札とする",
      "string_ko": "모두 버리기",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Сбросить всё"
    },
    "button_reshuffle": {
      "string_en": "Reshuffle Discard",
      "string_de": "Abwurfstapel einmischen",
      "string_cs": "Přimíchat odhozené",
      "string_es": null,
      "string_fr": "Mélanger la défausse",
      "string_it": null,
      "string_jp": "捨て札をシャッフルして戻す",
      "string_ko": "버린 카드 섞기",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Замешать сброс"
    },
    "button_title": {
      "string_en": "Hit the Road",
      "string_de": "Los geht's",
      "string_cs": "Jedeme!",
      "string_es": null,
      "string_fr": "C'est parti !",
      "string_it": null,
      "string_jp": "スタートする",
      "string_ko": "시작하기",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Поехали!"
    },
    "game_name": {
      "string_en": "Rough Roads",
      "string_de": "Krasse Strecken",
      "string_cs": "Drsné štreky",
      "string_es": null,
      "string_fr": "Routes chaotiques",
      "string_it": null,
      "string_jp": "ラフ・ロード",
      "string_ko": "고된 여정",
      "string_pl": null,
      "string_ro": null,
      "string_ru": "Ухабистый космос"
    },
    "scenario_picker_name": {
      "string_en": "Contract Picker",
      "string_de": "Contract Picker",
      "string_cs": "Contract Picker",
      "string_es": null,
      "string_fr": null,
      "string_it": null,
      "string_jp": null,
      "string_ko": null,
      "string_pl": null,
      "string_ro": null,
      "string_ru": null
    }
  }
}